#!/usr/bin/env python3
"""Load/save job hunt profile and apply preference boosts to scoring."""

from __future__ import annotations

import json
import re
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROFILE_PATH = ROOT / "context" / "job_hunt_profile.json"
USER_CONTEXT_PATH = ROOT / "context" / "USER_CONTEXT.md"


def default_profile() -> dict:
    return {
        "version": 1,
        "updated_at": "",
        "onboarding_complete": False,
        "identity": {"name": "", "email": "", "linkedin": "", "github": ""},
        "resume": {"path": "", "text_preview": ""},
        "location": {
            "remote_us": True,
            "hybrid_cities": [],
            "max_office_days_per_week": 2,
            "exclude_cities": ["new york", "san francisco", "seattle", "chicago", "boston"],
            "notes": "",
        },
        "compensation": {
            "floor_usd": 100_000,
            "target_low_usd": 120_000,
            "target_high_usd": 150_000,
        },
        "interests": [],
        "disinterests": [],
        "personality": {},
        "role_preferences": {
            "titles_love": [],
            "titles_avoid": [],
            "industries_love": [],
            "industries_avoid": [],
        },
        "followup_notes": [],
    }


def load_profile() -> dict | None:
    if not PROFILE_PATH.exists():
        return None
    try:
        data = json.loads(PROFILE_PATH.read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else None
    except (json.JSONDecodeError, OSError):
        return None


def save_profile(profile: dict) -> Path:
    PROFILE_PATH.parent.mkdir(parents=True, exist_ok=True)
    profile["updated_at"] = datetime.now().strftime("%Y-%m-%d %H:%M")
    profile["version"] = 1
    PROFILE_PATH.write_text(json.dumps(profile, indent=2) + "\n", encoding="utf-8")
    return PROFILE_PATH


def profile_ready(profile: dict | None) -> bool:
    return bool(profile and profile.get("onboarding_complete"))


def _blob(profile: dict) -> str:
    parts = [
        " ".join(profile.get("interests") or []),
        " ".join(profile.get("disinterests") or []),
        " ".join(profile.get("role_preferences", {}).get("titles_love") or []),
        " ".join(profile.get("role_preferences", {}).get("titles_avoid") or []),
        " ".join(profile.get("personality", {}).values())
        if isinstance(profile.get("personality"), dict)
        else "",
    ]
    return " ".join(parts).lower()


def preference_adjustment(title: str, description: str, profile: dict | None) -> tuple[int, str]:
    """
    Returns (delta_score, note) from user interests/disinterests in title+JD.
    Range roughly -3 to +3.
    """
    if not profile:
        return 0, ""
    t = (title or "").lower()
    d = (description or "").lower()
    blob = t + " " + d
    delta = 0
    notes: list[str] = []

    for phrase in profile.get("interests") or []:
        p = phrase.strip().lower()
        if len(p) < 3:
            continue
        if p in blob or p in t:
            delta += 1
            notes.append(f"+interest:{phrase[:40]}")

    for phrase in profile.get("disinterests") or []:
        p = phrase.strip().lower()
        if len(p) < 3:
            continue
        if p in blob or p in t:
            delta -= 2
            notes.append(f"-disinterest:{phrase[:40]}")

    for phrase in profile.get("role_preferences", {}).get("titles_love") or []:
        p = phrase.strip().lower()
        if p and p in t:
            delta += 1

    for phrase in profile.get("role_preferences", {}).get("titles_avoid") or []:
        p = phrase.strip().lower()
        if p and p in t:
            delta -= 2

    delta = max(-3, min(3, delta))
    return delta, "; ".join(notes[:3])


def comp_floor_usd(profile: dict | None) -> int:
    if not profile:
        return 100_000
    return int(profile.get("compensation", {}).get("floor_usd") or 100_000)


def hybrid_cities(profile: dict | None) -> list[str]:
    if not profile:
        return ["santa monica"]
    return [c.lower() for c in profile.get("location", {}).get("hybrid_cities") or []]


def remote_only(profile: dict | None) -> bool:
    if not profile:
        return False
    loc = profile.get("location") or {}
    return bool(loc.get("remote_us")) and not loc.get("hybrid_cities")


def write_user_context_md(profile: dict) -> Path:
    """Generate USER_CONTEXT.md from profile for Cursor agents."""
    ident = profile.get("identity") or {}
    comp = profile.get("compensation") or {}
    loc = profile.get("location") or {}
    pers = profile.get("personality") or {}
    lines = [
        "# Career profile (generated by job hunt onboarding)",
        "",
        f"> Updated: {profile.get('updated_at', '')}. Re-run `python scripts/job_hunt.py onboard` to refresh.",
        "",
        "## Identity",
        "",
        f"- **Name:** {ident.get('name', '')}",
        f"- **Location:** {loc.get('notes') or 'See location section'}",
        f"- **Email:** {ident.get('email', '')}",
        f"- **LinkedIn:** {ident.get('linkedin', '')}",
        f"- **GitHub:** {ident.get('github', '')}",
        "",
        "## Targets",
        "",
        f"- **Roles (love):** {', '.join(profile.get('role_preferences', {}).get('titles_love') or []) or 'see interests'}",
        f"- **Comp:** floor ${comp.get('floor_usd', 100000):,}; target ${comp.get('target_low_usd', 120000):,}-${comp.get('target_high_usd', 150000):,}",
        f"- **Remote US:** {loc.get('remote_us', True)}",
        f"- **Hybrid cities:** {', '.join(loc.get('hybrid_cities') or []) or 'none'}",
        f"- **Max office days/week:** {loc.get('max_office_days_per_week', 2)}",
        "",
        "## Interests (detailed)",
        "",
    ]
    for item in profile.get("interests") or []:
        lines.append(f"- {item}")
    lines += ["", "## Disinterests (hard avoid)", ""]
    for item in profile.get("disinterests") or []:
        lines.append(f"- {item}")
    lines += ["", "## Personality / work style", ""]
    for k, v in pers.items():
        lines.append(f"- **{k.replace('_', ' ').title()}:** {v}")
    if profile.get("followup_notes"):
        lines += ["", "## Onboarding follow-ups", ""]
        for n in profile["followup_notes"]:
            lines.append(f"- {n}")
    lines += [
        "",
        "## Blacklist (from onboarding)",
        "",
        "- " + "\n- ".join(profile.get("disinterests") or ["see above"]),
        "",
    ]
    USER_CONTEXT_PATH.write_text("\n".join(lines), encoding="utf-8")
    return USER_CONTEXT_PATH


def extract_resume_signals(text: str) -> dict:
    """Lightweight resume parse (no PDF dependency required)."""
    t = text.lower()
    skills = []
    for kw in (
        "python", "sql", "vba", "excel", "salesforce", "hubspot", "llm", "gpt",
        "automation", "power automate", "playwright", "supabase", "react",
    ):
        if kw in t:
            skills.append(kw)
    years = None
    m = re.search(r"(\d+)\+?\s*years?", t)
    if m:
        years = int(m.group(1))
    titles = []
    for phrase in (
        "business operations", "operations analyst", "account manager",
        "revops", "product ops", "implementation", "data analyst",
    ):
        if phrase in t:
            titles.append(phrase)
    return {"skills": skills, "years_mentioned": years, "title_signals": titles}
